# Generated by Django 5.2.15 on 2026-06-30 02:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField(default=5)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('is_online', models.BooleanField(default=True)),
                ('battery_level', models.PositiveSmallIntegerField(default=80)),
                ('network_name', models.CharField(blank=True, max_length=128)),
                ('firmware_version', models.CharField(default='v1.0.0', max_length=32)),
                ('volume', models.FloatField(default=0.6)),
                ('voice_name', models.CharField(default='软萌小鸭音', max_length=64)),
                ('last_online_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.childprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('child_speech', models.TextField()),
                ('duck_reply', models.TextField()),
                ('emotion', models.CharField(choices=[('happy', '开心'), ('curious', '好奇'), ('sad', '低落'), ('scared', '害怕'), ('calm', '平静')], default='curious', max_length=24)),
                ('risk_level', models.CharField(choices=[('normal', '正常'), ('attention', '需关注'), ('high_risk', '高风险')], default='normal', max_length=24)),
                ('full_conversation', models.TextField(blank=True)),
                ('emotion_analysis', models.TextField(blank=True)),
                ('safety_judgement', models.TextField(blank=True)),
                ('parent_note', models.TextField(blank=True)),
                ('flagged', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.childprofile')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField()),
                ('battery_level', models.PositiveSmallIntegerField()),
                ('network_name', models.CharField(blank=True, max_length=128)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('privacy', '隐私政策'), ('terms', '用户协议')], max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_latest', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'is_latest'], name='core_legald_type_182b39_idx')],
                'unique_together': {('type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('relation', models.CharField(default='家长', max_length=32)),
                ('avatar_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('feature', '功能建议'), ('device', '设备问题'), ('conversation', '对话内容'), ('safety', '安全提醒'), ('other', '其他')], max_length=32)),
                ('content', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=128)),
                ('client_info', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='core.parentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='childprofile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.parentprofile'),
        ),
        migrations.CreateModel(
            name='SafetySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensitive_topic_filter', models.BooleanField(default=True)),
                ('stranger_info_alert', models.BooleanField(default=True)),
                ('negative_emotion_alert', models.BooleanField(default=True)),
                ('night_usage_alert', models.BooleanField(default=True)),
                ('blocked_keywords', models.JSONField(blank=True, default=list)),
                ('reply_style', models.CharField(choices=[('gentle_companion', '温柔陪伴'), ('knowledge', '知识启蒙'), ('story', '故事模式'), ('short', '简短回答')], default='gentle_companion', max_length=32)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_settings', to='core.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_daily_minutes', models.PositiveSmallIntegerField(default=60)),
                ('sleep_start', models.CharField(default='21:00', max_length=5)),
                ('sleep_end', models.CharField(default='07:00', max_length=5)),
                ('nap_do_not_disturb', models.BooleanField(default=True)),
                ('weekly_plan', models.JSONField(blank=True, default=dict)),
                ('paused', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_settings', to='core.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读')], default='unread', max_length=16)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.childprofile')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['child', 'status', '-created_at'], name='core_alert_child_i_940447_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('child', '孩子'), ('duck', '小黄鸭')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='core.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='core_conver_convers_94c09e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('conversation_count', models.PositiveIntegerField(default=0)),
                ('companion_minutes', models.PositiveIntegerField(default=0)),
                ('story_count', models.PositiveIntegerField(default=0)),
                ('learning_interactions', models.PositiveIntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage_stats', to='core.childprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['child', '-date'], name='core_dailyu_child_i_6591f0_idx')],
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['child', '-started_at'], name='core_conver_child_i_ad811c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['risk_level', '-started_at'], name='core_conver_risk_le_807e74_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatuslog',
            index=models.Index(fields=['device', '-recorded_at'], name='core_device_device__cb0dd7_idx'),
        ),
    ]
